<?php
if (!defined('ABSPATH')) { exit; }

/** Own Stripe fulfillment so browser returns and webhooks cannot create two CTCL orders. */
class CTCL_Stripe_Checkout {
    const DB_VERSION = '2';
    const API_VERSION = '2026-09-30.endive';
    public function __construct() {
        if (get_option('ctcl_stripe_db_version') !== self::DB_VERSION) { self::install(); }
        add_action('wp_ajax_ctcl_stripe_session', array($this, 'createSession'));
        add_action('wp_ajax_nopriv_ctcl_stripe_session', array($this, 'createSession'));
        add_action('rest_api_init', function () {
            register_rest_route('ctcl-stripe/v1', '/webhook', array('methods' => 'POST', 'callback' => array($this, 'webhook'), 'permission_callback' => '__return_true'));
        });
        add_filter('pre_render_block', array($this, 'renderReturn'), 10, 2);
        add_action('ctcl_stripe_cleanup', array($this, 'cleanup'));
        if (!wp_next_scheduled('ctcl_stripe_cleanup')) { wp_schedule_event(time() + DAY_IN_SECONDS, 'daily', 'ctcl_stripe_cleanup'); }
    }
    private static function table() { global $wpdb; return $wpdb->prefix . 'ctclStripeCheckouts'; }
    public static function install() {
        global $wpdb;
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        $table = self::table();
        $collate = $wpdb->get_charset_collate();
        dbDelta("CREATE TABLE $table (
            attempt varchar(64) NOT NULL,
            session_id varchar(255) DEFAULT NULL,
            order_id varchar(32) NOT NULL,
            fingerprint char(64) NOT NULL,
            details longtext NOT NULL,
            environment varchar(4) NOT NULL,
            state varchar(20) NOT NULL DEFAULT 'open',
            created datetime NOT NULL,
            updated datetime NOT NULL,
            PRIMARY KEY  (attempt),
            UNIQUE KEY session_id (session_id),
            UNIQUE KEY order_id (order_id)
        ) $collate;");
        if (!get_option('ctcl_stripe_integration_identifier')) {
            $suffix = '';
            for ($i = 0; $i < 8; $i++) { $suffix .= chr(random_int(97, 122)); }
            update_option('ctcl_stripe_integration_identifier', 'ctcl_checkout_' . $suffix, false);
        }
        self::repairLegacyOrderIds();
        update_option('ctcl_stripe_db_version', self::DB_VERSION, false);
    }
    /** Core renders order IDs as Unix seconds; reserve one under a database lock. */
    private static function nextOrderId($timestamp) {
        global $wpdb;
        $id = (int) $timestamp;
        while ($wpdb->get_var($wpdb->prepare('SELECT order_id FROM ' . self::table() . ' WHERE order_id = %s', (string) $id)) || $wpdb->get_var($wpdb->prepare("SELECT orderId FROM {$wpdb->prefix}ctclOrders WHERE orderId = %s", (string) $id))) { $id++; }
        return (string) $id;
    }
    private static function lockName() { global $wpdb; return 'ctcl_stripe_ids_' . substr(hash('sha256', DB_NAME . $wpdb->prefix), 0, 24); }
    private function createDraft($attempt, $fingerprint, $data, $test) {
        global $wpdb;
        $lock = self::lockName();
        if ((int) $wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s, 10)', $lock)) !== 1) { throw new \RuntimeException(__('Checkout is busy. Please try again.', 'ctcl-stripe')); }
        try {
            $row = $this->find('attempt', $attempt);
            if (!$row) {
                $now = current_time('mysql', true);
                $saved = $wpdb->insert(self::table(), array('attempt' => $attempt, 'order_id' => self::nextOrderId(time()), 'fingerprint' => $fingerprint, 'details' => wp_json_encode($data), 'environment' => $test ? 'test' : 'live', 'state' => 'open', 'created' => $now, 'updated' => $now));
                if (!$saved) { throw new \RuntimeException(__('Checkout could not be saved. Please try again.', 'ctcl-stripe')); }
                $row = $this->find('attempt', $attempt);
            }
            if (!$row || $row['fingerprint'] !== $fingerprint) { throw new \RuntimeException(__('Checkout details changed. Refresh your payment form before paying.', 'ctcl-stripe')); }
            return $row;
        } finally { $wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)', $lock)); }
    }
    /** Repair only IDs generated by early 2.0 builds, retaining Stripe's original reference. */
    public static function repairLegacyOrderIds() {
        global $wpdb;
        $lock = self::lockName();
        if ((int) $wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s, 10)', $lock)) !== 1) { return; }
        try {
            $rows = $wpdb->get_results('SELECT * FROM ' . self::table(), ARRAY_A);
            foreach ($rows as $row) {
                if (!preg_match('/^[0-9]{16}$/', $row['order_id'])) { continue; }
                $timestamp = (int) substr($row['order_id'], 0, 10);
                if (abs(strtotime($row['created'] . ' UTC') - $timestamp) > 60) { continue; }
                $order = $wpdb->get_row($wpdb->prepare("SELECT orderDetail FROM {$wpdb->prefix}ctclOrders WHERE orderId = %s", $row['order_id']), ARRAY_A);
                $detail = $order ? json_decode($order['orderDetail'], true) : null;
                if ($order && (!is_array($detail) || ($detail['stripe_session_id'] ?? '') !== $row['session_id'])) { continue; }
                $id = self::nextOrderId($timestamp);
                $wpdb->query('START TRANSACTION');
                $saved = $wpdb->update(self::table(), array('order_id' => $id), array('attempt' => $row['attempt']));
                if ($order) {
                    $detail['stripe_original_order_id'] = $row['order_id'];
                    $detail['order_id'] = $id;
                    $saved = $saved && false !== $wpdb->update($wpdb->prefix . 'ctclOrders', array('orderId' => $id, 'orderDetail' => wp_json_encode($detail)), array('orderId' => $row['order_id']));
                }
                $wpdb->query($saved ? 'COMMIT' : 'ROLLBACK');
            }
        } finally { $wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)', $lock)); }
    }
    public static function testMode() { return '1' === (string) get_option('ctcl_stripe_test_mode'); }
    public static function key($kind, $test = null) {
        if ($test === null) { $test = self::testMode(); }
        return trim((string) get_option('ctc_stripe_' . ($test ? 'test' : 'live') . '_' . $kind . '_key', ''));
    }
    public static function signingSecret($test) { return trim((string) get_option('ctcl_stripe_' . ($test ? 'test' : 'live') . '_webhook_secret', '')); }
    public static function available() {
        return '1' === (string) get_option('ctcl_activate_stripe') && self::key('publishable') !== '' && self::key('secret') !== '';
    }
    private function client($test) {
        return new \Stripe\StripeClient(array('api_key' => self::key('secret', $test), 'stripe_version' => self::API_VERSION));
    }
    public static function currency() {
        $currency = strtolower(trim((string) get_option('ctcl_currency', 'USD')));
        return preg_match('/^[a-z]{3}$/', $currency) ? $currency : 'usd';
    }
    /** Stripe amounts are in minor units; these currencies have no decimal minor unit. */
    public static function minorAmount($amount, $currency) {
        $zero = array('bif','clp','djf','gnf','jpy','kmf','krw','mga','pyg','rwf','vnd','vuv','xaf','xof','xpf');
        if (!is_numeric($amount) || !is_finite((float) $amount) || (float) $amount <= 0) { throw new \RuntimeException(__('The order total must be greater than zero.', 'ctcl-stripe')); }
        if (in_array($currency, array('bhd','jod','kwd','omr','tnd'), true)) { throw new \RuntimeException(__('This checkout does not yet support three-decimal currencies.', 'ctcl-stripe')); }
        $factor = in_array($currency, $zero, true) ? 1 : 100;
        $scaled = (float) $amount * $factor;
        if (abs($scaled - round($scaled)) > 0.001 || $scaled > 99999999) { throw new \RuntimeException(__('The total is not valid for the store currency.', 'ctcl-stripe')); }
        if (in_array($currency, array('isk', 'ugx'), true) && fmod((float) $amount, 1) !== 0.0) { throw new \RuntimeException(__('The currency requires a whole-number total.', 'ctcl-stripe')); }
        // ISK uses a two-decimal API representation despite being a zero-decimal currency.
        return (int) round($scaled);
    }
    private function validatedCheckout($raw) {
        if (!is_array($raw)) { throw new \RuntimeException(__('The checkout details could not be read.', 'ctcl-stripe')); }
        $data = array();
        foreach (array('ctcl-co-first-name','ctcl-co-last-name','checkout-street-address-1','checkout-street-address-2','checkout-city','checkout-state','checkout-zip-code','checkout-country','checkout-special-instruction','checkout-phone-number','ctcl_coupon_code','ctcl_checkout_page') as $field) {
            $data[$field] = sanitize_text_field(is_string($raw[$field] ?? null) ? $raw[$field] : '');
        }
        $data['checkout-email-address'] = sanitize_email(is_string($raw['checkout-email-address'] ?? null) ? $raw['checkout-email-address'] : '');
        if (!$data['ctcl-co-first-name'] || !$data['ctcl-co-last-name'] || !is_email($data['checkout-email-address'])) {
            throw new \RuntimeException(__('Complete your name and email address before continuing.', 'ctcl-stripe'));
        }
        $data['payment_option'] = 'ctcl_stripe';
        $data['payment_type'] = sanitize_text_field((string) get_option('ctcl_stripe_display_label', 'Stripe')) ?: 'Stripe';
        $data['shipping_option'] = is_string($raw['shipping_option'] ?? null) ? $raw['shipping_option'] : '';
        $selected = null;
        foreach ((array) apply_filters('ctcl_shipping_option_display', array()) as $shipping) {
            if (($shipping['id'] ?? '') === $data['shipping_option']) { $selected = $shipping; }
        }
        if (!$selected) { throw new \RuntimeException(__('Choose an available shipping option.', 'ctcl-stripe')); }
        $data['shipping_type'] = sanitize_text_field($selected['name']);
        if ($data['shipping_option'] !== 'store_pickup') {
            foreach (array('checkout-street-address-1','checkout-city','checkout-state','checkout-zip-code','checkout-country') as $field) {
                if (!$data[$field]) { throw new \RuntimeException(__('Complete your delivery address before continuing.', 'ctcl-stripe')); }
            }
        }
        foreach (array('items-total','shipping-total','tax-total','total-discount','sub-total') as $field) {
            $data[$field] = is_scalar($raw[$field] ?? null) ? (string) $raw[$field] : ($field === 'total-discount' ? '0' : '');
        }
        $data['products'] = $raw['products'] ?? array();
        if (!defined('CTCL_DIR_PATH')) { throw new \RuntimeException(__('Update CT Commerce Lite before using Stripe checkout.', 'ctcl-stripe')); }
        $validator = WP_PLUGIN_DIR . '/ctc-lite/classes/ctcl-checkout-validation.php';
        if (!class_exists('ctclCheckoutValidation') && is_readable($validator)) { require_once $validator; }
        if (!class_exists('ctclCheckoutValidation')) { throw new \RuntimeException(__('CT Commerce Lite 2.8.3 or later with server checkout validation is required.', 'ctcl-stripe')); }
        $validated = ctclCheckoutValidation::validate($data);
        if (is_wp_error($validated)) { throw new \RuntimeException($validated->get_error_message()); }
        return $validated;
    }
    private function find($field, $value) {
        global $wpdb;
        $column = $field === 'attempt' ? 'attempt' : 'session_id';
        return $wpdb->get_row($wpdb->prepare('SELECT * FROM ' . self::table() . " WHERE $column = %s", $value), ARRAY_A);
    }
    private function fail($message, $code = 400) { wp_send_json_error(array('message' => $message), $code); }
    public function createSession() {
        check_ajax_referer('ctcl_stripe_checkout', 'nonce');
        if (!self::available()) { $this->fail(__('Stripe is not configured. Choose another payment method.', 'ctcl-stripe')); }
        if (!self::testMode() && (!is_ssl() || self::signingSecret(false) === '')) {
            $this->fail(__('Live checkout requires HTTPS and a configured webhook signing secret.', 'ctcl-stripe'));
        }
        global $wpdb;
        try {
            $prefix = self::testMode() ? 'test' : 'live';
            if (!preg_match('/^pk_' . $prefix . '_[A-Za-z0-9]+$/', self::key('publishable')) || !preg_match('/^[sr]k_' . $prefix . '_[A-Za-z0-9]+$/', self::key('secret'))) {
                throw new \RuntimeException(__('Check that both API keys belong to the selected test or live environment.', 'ctcl-stripe'));
            }
            $raw = wp_unslash($_POST);
            $attempt = is_string($raw['attempt'] ?? null) ? $raw['attempt'] : '';
            if (!preg_match('/^[a-f0-9-]{32,64}$/i', $attempt)) { throw new \RuntimeException(__('Refresh checkout and try again.', 'ctcl-stripe')); }
            $data = $this->validatedCheckout($raw);
            $currency = self::currency();
            $amount = self::minorAmount($data['sub-total'], $currency);
            $data['stripe_currency'] = $currency;
            $test = self::testMode();
            $fingerprint = hash('sha256', wp_json_encode(array($data, $currency, $test)));
            $returnPage = is_string($raw['return_page'] ?? null) ? esc_url_raw($raw['return_page']) : '';
            $pageId = url_to_postid($returnPage);
            $page = get_post($pageId);
            if (!$page || $page->post_status !== 'publish' || !has_block('ctc-lite/ctc-lite-order-processing', $page)) {
                throw new \RuntimeException(__('Set the checkout payment page to a published CT Commerce Lite order-processing page.', 'ctcl-stripe'));
            }
            $returnPage = get_permalink($pageId);
            $row = $this->find('attempt', $attempt);
            if ($row && ($row['fingerprint'] !== $fingerprint || $row['environment'] !== ($test ? 'test' : 'live'))) {
                throw new \RuntimeException(__('Checkout details changed. Refresh your payment form before paying.', 'ctcl-stripe'));
            }
            if (!$row) {
                $row = $this->createDraft($attempt, $fingerprint, $data, $test);
            }
            $client = $this->client($test);
            // A changed checkout must retire its previous open Session before another can be paid.
            $previous = is_string($raw['previous_attempt'] ?? null) ? $raw['previous_attempt'] : '';
            $old = $previous && $previous !== $attempt ? $this->find('attempt', $previous) : null;
            if ($old && $old['session_id'] && $old['environment'] === ($test ? 'test' : 'live')) {
                $oldSession = $client->checkout->sessions->retrieve($old['session_id']);
                if ($oldSession->status === 'complete' && $old['state'] !== 'failed') {
                    wp_send_json_success(array('complete' => true, 'returnUrl' => add_query_arg(array('ctcl_stripe_return' => $previous, 'session_id' => $old['session_id']), $returnPage)));
                }
                if ($oldSession->status === 'open') { $client->checkout->sessions->expire($old['session_id']); }
            }
            $returnUrl = add_query_arg(array('ctcl_stripe_return' => $attempt), $returnPage);
            if ($row['session_id']) {
                $session = $client->checkout->sessions->retrieve($row['session_id']);
            } else {
                // CTCL owns product pricing, tax, discount and shipping. Charge its validated grand total exactly.
                $session = $client->checkout->sessions->create(array(
                    'mode' => 'payment', 'ui_mode' => 'elements',
                    'adaptive_pricing' => array('enabled' => false),
                    'customer_email' => $data['checkout-email-address'],
                    'line_items' => array(array('price_data' => array('currency' => $currency, 'unit_amount' => $amount, 'product_data' => array('name' => sprintf(__('Order %s', 'ctcl-stripe'), $row['order_id']))), 'quantity' => 1)),
                    'return_url' => $returnUrl . '&session_id={CHECKOUT_SESSION_ID}',
                    'client_reference_id' => $row['order_id'],
                    'metadata' => array('ctcl_attempt' => $attempt, 'ctcl_fingerprint' => $fingerprint),
                    'payment_intent_data' => array('metadata' => array('ctcl_order_id' => $row['order_id'])),
                    'integration_identifier' => get_option('ctcl_stripe_integration_identifier'),
                ), array('idempotency_key' => 'ctcl_' . $attempt));
                if (false === $wpdb->update(self::table(), array('session_id' => $session->id), array('attempt' => $attempt))) { throw new \RuntimeException(__('Checkout could not be saved. Please try again.', 'ctcl-stripe')); }
            }
            if ($session->status === 'expired' || $row['state'] === 'failed') { wp_send_json_error(array('expired' => true, 'message' => __('Your payment session ended. Continue again to start a new payment.', 'ctcl-stripe')), 400); }
            $url = add_query_arg('session_id', $session->id, $returnUrl);
            wp_send_json_success(array('clientSecret' => $session->status === 'open' ? $session->client_secret : null, 'sessionId' => $session->id, 'returnUrl' => $url, 'complete' => $session->status === 'complete', 'total' => strtoupper($currency) . ' ' . $data['sub-total']));
        } catch (\Stripe\Exception\ApiErrorException $error) {
            // Never return raw Stripe errors, credentials or request bodies to shoppers.
            $this->fail(__('Stripe could not start checkout. Please try again or choose another payment method.', 'ctcl-stripe'), 502);
        } catch (\Throwable $error) { $this->fail($error instanceof \RuntimeException ? $error->getMessage() : __('Checkout is temporarily unavailable. Please try again.', 'ctcl-stripe')); }
    }
    /** Check both paid status and binding to our immutable, server-validated snapshot. */
    public function fulfill($session) {
        global $wpdb;
        $row = $this->find('session_id', $session->id);
        if (!$row) { throw new \RuntimeException('Unknown checkout.'); }
        if ($session->payment_status !== 'paid') { return array('paid' => false, 'orderId' => $row['order_id']); }
        if (($session->metadata['ctcl_attempt'] ?? '') !== $row['attempt'] || ($session->metadata['ctcl_fingerprint'] ?? '') !== $row['fingerprint'] || (bool) $session->livemode !== ($row['environment'] === 'live')) { throw new \RuntimeException('Checkout binding mismatch.'); }
        if ($row['state'] === 'fulfilled') { return array('paid' => true, 'orderId' => $row['order_id']); }
        $data = json_decode($row['details'], true);
        if (!is_array($data) || ($data['stripe_currency'] ?? '') !== $session->currency || (int) $session->amount_total !== self::minorAmount($data['sub-total'], $session->currency)) { throw new \RuntimeException('Checkout amount mismatch.'); }
        // A short lease serializes webhook and browser fulfillment; a crashed worker can be retried.
        $claimed = $wpdb->query($wpdb->prepare('UPDATE ' . self::table() . " SET state = 'fulfilling', updated = UTC_TIMESTAMP() WHERE attempt = %s AND (state IN ('open','processing') OR (state = 'fulfilling' AND updated < DATE_SUB(UTC_TIMESTAMP(), INTERVAL 5 MINUTE)))", $row['attempt']));
        if (!$claimed) { throw new \RuntimeException('Order confirmation is in progress.'); }
        $data['order_id'] = $row['order_id'];
        $data['charge_result'] = true;
        $data['stripe_session_id'] = $session->id;
        $data['stripe_payment_intent'] = is_string($session->payment_intent) ? $session->payment_intent : $session->payment_intent->id;
        $orders = $wpdb->prefix . 'ctclOrders';
        $exists = $wpdb->get_var($wpdb->prepare("SELECT orderId FROM $orders WHERE orderId = %s", $row['order_id']));
        if (!$exists) {
            $inserted = $wpdb->insert($orders, array('orderId' => $row['order_id'], 'orderDetail' => wp_json_encode($data), 'orderStatus' => 'pending', 'vendorNote' => ''), array('%s','%s','%s','%s'));
            if (!$inserted) {
                $wpdb->update(self::table(), array('state' => 'open'), array('attempt' => $row['attempt']));
                throw new \RuntimeException('Order storage failed.');
            }
            // Match CTCL's existing hooks, shipping notes and confirmation email flow.
            apply_filters('ctcl_data_for_ml', $data);
            do_action('ctcl-order-placed', $data);
            $shipped = apply_filters('ctcl_shipping_option_' . $data['shipping_option'], $data);
            $body = apply_filters('ctcl_custom_email_body', '', $shipped);
            if (!$body) { $body = (new ctclHtml())->createEmailBody($shipped); }
            $sent = (new ctclProcessing())->sendConfirmationEmail($data['checkout-email-address'], get_option('ctcl_email_subject'), $body, true);
            $data['stripe_email_sent'] = (bool) $sent;
            $wpdb->update($orders, array('orderDetail' => wp_json_encode($data)), array('orderId' => $row['order_id']));
        }
        $wpdb->update(self::table(), array('state' => 'fulfilled', 'details' => '{}', 'updated' => current_time('mysql', true)), array('attempt' => $row['attempt']));
        return array('paid' => true, 'orderId' => $row['order_id']);
    }
    public function webhook($request) {
        $event = null;
        foreach (array(true, false) as $test) {
            $secret = self::signingSecret($test);
            if ($secret === '') { continue; }
            try {
                $candidate = \Stripe\Webhook::constructEvent($request->get_body(), $request->get_header('stripe-signature'), $secret);
                if ((bool) $candidate->livemode === !$test) { $event = $candidate; break; }
            } catch (\Throwable $error) { /* Try the other environment's signing secret. */ }
        }
        if (!$event) { return new WP_Error('ctcl_stripe_signature', 'Invalid webhook signature.', array('status' => 400)); }
        if (!in_array($event->type, array('checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed'), true)) { return new WP_REST_Response(array('received' => true)); }
        $session = $event->data->object;
        $row = $this->find('session_id', $session->id);
        // Other Stripe integrations on the same account are not CTCL checkouts.
        if (!$row) { return new WP_REST_Response(array('received' => true)); }
        try {
            if ($event->type === 'checkout.session.async_payment_failed') {
                global $wpdb;
                $wpdb->query($wpdb->prepare('UPDATE ' . self::table() . " SET state = 'failed' WHERE attempt = %s AND state != 'fulfilled'", $row['attempt']));
            } else {
                $this->fulfill($session);
            }
            return new WP_REST_Response(array('received' => true));
        } catch (\Throwable $error) { return new WP_Error('ctcl_stripe_retry', 'Order confirmation needs retry.', array('status' => 500)); }
    }
    public function renderReturn($pre, $block) {
        if (($block['blockName'] ?? '') !== 'ctc-lite/ctc-lite-order-processing') { return $pre; }
        if (($_POST['payment_option'] ?? '') === 'ctcl_stripe') {
            return '<p>' . esc_html__('Use the secure Stripe payment form on checkout to complete this order.', 'ctcl-stripe') . '</p>';
        }
        $attempt = isset($_GET['ctcl_stripe_return']) && is_string($_GET['ctcl_stripe_return']) ? sanitize_text_field(wp_unslash($_GET['ctcl_stripe_return'])) : '';
        $sessionId = isset($_GET['session_id']) && is_string($_GET['session_id']) ? sanitize_text_field(wp_unslash($_GET['session_id'])) : '';
        if (!$attempt) { return $pre; }
        nocache_headers();
        $row = $this->find('attempt', $attempt);
        if (!$row || !$sessionId || !hash_equals((string) $row['session_id'], $sessionId)) { return '<p>' . esc_html__('This payment return could not be verified. Please contact the store if you have already paid.', 'ctcl-stripe') . '</p>'; }
        try {
            $session = $this->client($row['environment'] === 'test')->checkout->sessions->retrieve($sessionId);
            $result = $this->fulfill($session);
            if (!$result['paid']) {
                if ($session->status !== 'complete' || $row['state'] === 'failed') {
                    return '<div class="ctcl-stripe-result"><h2>' . esc_html__('Payment not completed', 'ctcl-stripe') . '</h2><p>' . esc_html__('Your order has not been placed. Return to checkout to try again or choose another payment method.', 'ctcl-stripe') . '</p></div>';
                }
                return '<div class="ctcl-stripe-result"><h2>' . esc_html__('Payment awaiting confirmation', 'ctcl-stripe') . '</h2><p>' . esc_html__('Your order will be placed when Stripe confirms the payment. Do not pay again while it is processing.', 'ctcl-stripe') . '</p></div>';
            }
            $clearAttempt = '(function(){try{for(var i=sessionStorage.length-1;i>=0;i--){var key=sessionStorage.key(i);if(key.indexOf("ctclStripeAttempt:")===0){var value=JSON.parse(sessionStorage.getItem(key));if(value&&value.attempt===' . wp_json_encode($attempt) . '){sessionStorage.removeItem(key);}}}}catch(e){}})();';
            // Block themes can render this block before wp_enqueue_scripts registers the controller.
            add_action('wp_footer', function () use ($clearAttempt) { wp_print_inline_script_tag($clearAttempt); }, 30);
            return '<div id="ctcl-order-sucesfully-placed" class="ctcl-stripe-result"><h2>' . esc_html__('Thank you. Your order is placed.', 'ctcl-stripe') . '</h2><p>' . esc_html__('Payment confirmed by Stripe.', 'ctcl-stripe') . '</p><p>' . esc_html__('Order ID:', 'ctcl-stripe') . ' <strong>' . esc_html($result['orderId']) . '</strong></p></div>';
        } catch (\Throwable $error) { return '<p>' . esc_html__('Your payment is being checked. Refresh this page shortly or contact the store. Do not pay again.', 'ctcl-stripe') . '</p>'; }
    }
    public function cleanup() {
        global $wpdb;
        // No unpaid drafts live forever; fulfilled orders remain in the CTCL orders table.
        $wpdb->query('DELETE FROM ' . self::table() . " WHERE created < DATE_SUB(UTC_TIMESTAMP(), INTERVAL 30 DAY) AND state != 'fulfilling'");
    }
}
